// MaterialXSIPlugin
// Initial code generated by Softimage SDK Wizard
// Executed Tue Apr 30 20:28:17 UTC+0500 2024 by Shekn
// 
// Tip: You need to compile the generated code before you can load the plug-in.
// After you compile the plug-in, you can load it by clicking Update All in the Plugin Manager.
#include <xsi_application.h>
#include <xsi_context.h>
#include <xsi_pluginregistrar.h>
#include <xsi_status.h>

SICALLBACK XSILoadPlugin(XSI::PluginRegistrar& in_reg)
{
	in_reg.PutAuthor("Shekn");
	in_reg.PutName("MaterialXSIPlugin");
	in_reg.PutVersion(1, 0);
	//RegistrationInsertionPoint - do not remove this line

	return XSI::CStatus::OK;
}

SICALLBACK XSIUnloadPlugin(const XSI::PluginRegistrar& in_reg)
{
	XSI::CString strPluginName;
	strPluginName = in_reg.GetName();
	XSI::Application().LogMessage(strPluginName + " has been unloaded.", XSI::siVerboseMsg);
	return XSI::CStatus::OK;
}

